#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Siemens Questa Advanced Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Jan 21 14:24:55 KST 2026
# SW Build 6060944 on Thu Mar 06 19:10:09 MST 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
bin_path="/home/holee/TOOLS/QuestaBase_2024.3/questa_base/bin"
set -Eeuo pipefail
source test_bench_elaborate.do 2>&1 | tee elaborate.log

