#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Siemens Questa Advanced Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Jan 21 14:24:58 KST 2026
# SW Build 6060944 on Thu Mar 06 19:10:09 MST 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
bin_path="/home/holee/TOOLS/QuestaBase_2024.3/questa_base/bin"
set -Eeuo pipefail
$bin_path/vsim -64  -do "do {test_bench_simulate.do}" -l simulate.log

