onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider {read data mux}
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/sys_clk
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/sys_rst
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/eim_clk
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/eim_rst
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/csi_done
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/dummy_get_image
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/exist_get_image
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/dsp_image_height
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/max_v_count
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/max_h_count
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/FSM_aed_read_index
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/FSM_read_index
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/read_data_start
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/roic_read_data_a
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/roic_read_data_b
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/valid_read_mem
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/read_axis_tready
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/read_axis_tlast
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/read_data_valid
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/read_data_out_a
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/read_data_out_b
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/read_frame_start
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/read_frame_reset
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/data_read_req
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/tx_eim_rst
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/s_h_count
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/s_v_count
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/s_max_h_count
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/s_max_v_count
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/s_sync_gen_en
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/s_axis_tvalid
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/s_axis_tvalid_1d
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/s_axis_tvalid_2d
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/s_axis_tvalid_3d
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/s_read_axis_tready
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/s_axis_tlast
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/s_axis_tlast_1d
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/s_axis_tlast_2d
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/s_axis_tlast_3d
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/s_valid_read_mem
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/s_dummy_read_index
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/s_axis_read_mem
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/read_mem_index
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/test_pattern_row
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/pattern_offset
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/line_offset
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/hsync
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/hi_hsync
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/hi_hsync_all
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/lo_hsync
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/sig_hsync
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/sig_hsync_1d
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/sig_hsync_2d
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/up_hsync_keep_hi
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/down_hsync_keep_hi
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/hsync_keep_hi
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/hsync_keep_hi_cnt
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/rst_hsync_cnt
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/rst_hsync_cnt_dly
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/inc_hsync_cnt
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/hsync_cnt
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/s_read_data_start
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/FSM_read_index_eim_1d
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/FSM_read_index_eim_2d
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/FSM_read_index_eim_3d
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/FSM_read_index_eim_4d
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/FSM_read_index_eim_5d
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/sig_vsync
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/hi_vsync
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/lo_vsync
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/up_vsync_keep_hi
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/down_vsync_keep_hi
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/vsync_keep_hi
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/vsync_keep_hi_cnt
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/FSM_read_index_sys_1d
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/FSM_read_index_sys_2d
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/tx_sys_rst
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/s_dummy_start
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/s_dummy_get_image_1d
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/s_dummy_get_image_2d
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/s_dummy_valid
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/s_dummy_valid_count
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/read_mem
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/read_mem_1d
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/read_mem_2d
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/end_read_mem
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/start_read_mem
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/s_tuser_0_dly
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/s_v_sync
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/s_h_sync
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/s_tuser_0
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/s_hsync_FSM_read_index
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/s_hsync_dly_FSM_read_index
add wave -noupdate /test_bench/blue_hd_uut/read_data_mux_inst/read_hsync
add wave -noupdate -divider init
add wave -noupdate /test_bench/blue_hd_uut/init_inst/fsm_clk
add wave -noupdate /test_bench/blue_hd_uut/init_inst/reset
add wave -noupdate /test_bench/blue_hd_uut/init_inst/en_pwr_off
add wave -noupdate /test_bench/blue_hd_uut/init_inst/en_pwr_dwn
add wave -noupdate /test_bench/blue_hd_uut/init_inst/init_rst
add wave -noupdate /test_bench/blue_hd_uut/init_inst/pwr_init_step1
add wave -noupdate /test_bench/blue_hd_uut/init_inst/pwr_init_step2
add wave -noupdate /test_bench/blue_hd_uut/init_inst/pwr_init_step3
add wave -noupdate /test_bench/blue_hd_uut/init_inst/pwr_init_step4
add wave -noupdate /test_bench/blue_hd_uut/init_inst/pwr_init_step5
add wave -noupdate /test_bench/blue_hd_uut/init_inst/pwr_init_step6
add wave -noupdate /test_bench/blue_hd_uut/init_inst/roic_reset
add wave -noupdate /test_bench/blue_hd_uut/init_inst/en_pwr_off_1d
add wave -noupdate /test_bench/blue_hd_uut/init_inst/en_pwr_off_2d
add wave -noupdate /test_bench/blue_hd_uut/init_inst/start_pwr_off
add wave -noupdate /test_bench/blue_hd_uut/init_inst/start_pwr_on
add wave -noupdate /test_bench/blue_hd_uut/init_inst/pwr_off
add wave -noupdate /test_bench/blue_hd_uut/init_inst/pwr_on
add wave -noupdate /test_bench/blue_hd_uut/init_inst/init_step1
add wave -noupdate /test_bench/blue_hd_uut/init_inst/init_step2
add wave -noupdate /test_bench/blue_hd_uut/init_inst/init_step3
add wave -noupdate /test_bench/blue_hd_uut/init_inst/init_step4
add wave -noupdate /test_bench/blue_hd_uut/init_inst/init_step5
add wave -noupdate /test_bench/blue_hd_uut/init_inst/init_step6
add wave -noupdate /test_bench/blue_hd_uut/init_inst/init_step6_1d
add wave -noupdate /test_bench/blue_hd_uut/init_inst/init_step6_2d
add wave -noupdate /test_bench/blue_hd_uut/init_inst/en_pwr_dwn_1d
add wave -noupdate /test_bench/blue_hd_uut/init_inst/en_pwr_dwn_2d
add wave -noupdate /test_bench/blue_hd_uut/init_inst/start_pwr_dwn_off
add wave -noupdate /test_bench/blue_hd_uut/init_inst/start_pwr_dwn_on
add wave -noupdate /test_bench/blue_hd_uut/init_inst/pwr_dwn_off
add wave -noupdate /test_bench/blue_hd_uut/init_inst/pwr_dwn_on
add wave -noupdate /test_bench/blue_hd_uut/init_inst/pwr_dwn_step1
add wave -noupdate /test_bench/blue_hd_uut/init_inst/pwr_dwn_step2
add wave -noupdate /test_bench/blue_hd_uut/init_inst/pwr_dwn_step3
add wave -noupdate /test_bench/blue_hd_uut/init_inst/pwr_dwn_step4
add wave -noupdate /test_bench/blue_hd_uut/init_inst/pwr_dwn_step5
add wave -noupdate /test_bench/blue_hd_uut/init_inst/hi_init_rst
add wave -noupdate /test_bench/blue_hd_uut/init_inst/sig_init_rst
add wave -noupdate /test_bench/blue_hd_uut/init_inst/step_delay
add wave -noupdate /test_bench/blue_hd_uut/init_inst/step_delay_1d
add wave -noupdate /test_bench/blue_hd_uut/init_inst/step_delay_2d
add wave -noupdate /test_bench/blue_hd_uut/init_inst/step_delay_3d
add wave -noupdate /test_bench/blue_hd_uut/init_inst/step_delay_4d
add wave -noupdate /test_bench/blue_hd_uut/init_inst/counter1
add wave -noupdate /test_bench/blue_hd_uut/init_inst/counter2
add wave -noupdate -divider top
add wave -noupdate /test_bench/blue_hd_uut/nRST
add wave -noupdate /test_bench/blue_hd_uut/MCLK_50M_p
add wave -noupdate /test_bench/blue_hd_uut/MCLK_50M_n
add wave -noupdate /test_bench/blue_hd_uut/mipi_phy_if_clk_hs_p
add wave -noupdate /test_bench/blue_hd_uut/mipi_phy_if_clk_hs_n
add wave -noupdate /test_bench/blue_hd_uut/mipi_phy_if_clk_lp_p
add wave -noupdate /test_bench/blue_hd_uut/mipi_phy_if_clk_lp_n
add wave -noupdate /test_bench/blue_hd_uut/mipi_phy_if_data_hs_p
add wave -noupdate /test_bench/blue_hd_uut/mipi_phy_if_data_hs_n
add wave -noupdate /test_bench/blue_hd_uut/mipi_phy_if_data_lp_p
add wave -noupdate /test_bench/blue_hd_uut/mipi_phy_if_data_lp_n
add wave -noupdate /test_bench/blue_hd_uut/SCLK
add wave -noupdate /test_bench/blue_hd_uut/SSB
add wave -noupdate /test_bench/blue_hd_uut/MOSI
add wave -noupdate /test_bench/blue_hd_uut/MISO
add wave -noupdate /test_bench/blue_hd_uut/ROIC_TP_SEL
add wave -noupdate /test_bench/blue_hd_uut/ROIC_SYNC
add wave -noupdate /test_bench/blue_hd_uut/ROIC_MCLK0
add wave -noupdate /test_bench/blue_hd_uut/ROIC_SPI_SCK
add wave -noupdate /test_bench/blue_hd_uut/ROIC_SPI_SDI
add wave -noupdate /test_bench/blue_hd_uut/ROIC_SPI_SDO
add wave -noupdate /test_bench/blue_hd_uut/ROIC_SPI_SEN_N
add wave -noupdate /test_bench/blue_hd_uut/DCLKP_0
add wave -noupdate /test_bench/blue_hd_uut/DCLKP_1
add wave -noupdate /test_bench/blue_hd_uut/DCLKP_2
add wave -noupdate /test_bench/blue_hd_uut/DCLKP_3
add wave -noupdate /test_bench/blue_hd_uut/DCLKP_4
add wave -noupdate /test_bench/blue_hd_uut/DCLKP_5
add wave -noupdate /test_bench/blue_hd_uut/DCLKP_6
add wave -noupdate /test_bench/blue_hd_uut/DCLKP_7
add wave -noupdate /test_bench/blue_hd_uut/DCLKP_8
add wave -noupdate /test_bench/blue_hd_uut/DCLKP_9
add wave -noupdate /test_bench/blue_hd_uut/DCLKP_10
add wave -noupdate /test_bench/blue_hd_uut/DCLKP_11
add wave -noupdate /test_bench/blue_hd_uut/DCLKP_12
add wave -noupdate /test_bench/blue_hd_uut/DCLKP_13
add wave -noupdate /test_bench/blue_hd_uut/DCLKN_0
add wave -noupdate /test_bench/blue_hd_uut/DCLKN_1
add wave -noupdate /test_bench/blue_hd_uut/DCLKN_2
add wave -noupdate /test_bench/blue_hd_uut/DCLKN_3
add wave -noupdate /test_bench/blue_hd_uut/DCLKN_4
add wave -noupdate /test_bench/blue_hd_uut/DCLKN_5
add wave -noupdate /test_bench/blue_hd_uut/DCLKN_6
add wave -noupdate /test_bench/blue_hd_uut/DCLKN_7
add wave -noupdate /test_bench/blue_hd_uut/DCLKN_8
add wave -noupdate /test_bench/blue_hd_uut/DCLKN_9
add wave -noupdate /test_bench/blue_hd_uut/DCLKN_10
add wave -noupdate /test_bench/blue_hd_uut/DCLKN_11
add wave -noupdate /test_bench/blue_hd_uut/DCLKN_12
add wave -noupdate /test_bench/blue_hd_uut/DCLKN_13
add wave -noupdate /test_bench/blue_hd_uut/FCLKP_0
add wave -noupdate /test_bench/blue_hd_uut/FCLKP_1
add wave -noupdate /test_bench/blue_hd_uut/FCLKP_2
add wave -noupdate /test_bench/blue_hd_uut/FCLKP_3
add wave -noupdate /test_bench/blue_hd_uut/FCLKP_4
add wave -noupdate /test_bench/blue_hd_uut/FCLKP_5
add wave -noupdate /test_bench/blue_hd_uut/FCLKP_6
add wave -noupdate /test_bench/blue_hd_uut/FCLKP_7
add wave -noupdate /test_bench/blue_hd_uut/FCLKP_8
add wave -noupdate /test_bench/blue_hd_uut/FCLKP_9
add wave -noupdate /test_bench/blue_hd_uut/FCLKP_10
add wave -noupdate /test_bench/blue_hd_uut/FCLKP_11
add wave -noupdate /test_bench/blue_hd_uut/FCLKP_12
add wave -noupdate /test_bench/blue_hd_uut/FCLKP_13
add wave -noupdate /test_bench/blue_hd_uut/FCLKN_0
add wave -noupdate /test_bench/blue_hd_uut/FCLKN_1
add wave -noupdate /test_bench/blue_hd_uut/FCLKN_2
add wave -noupdate /test_bench/blue_hd_uut/FCLKN_3
add wave -noupdate /test_bench/blue_hd_uut/FCLKN_4
add wave -noupdate /test_bench/blue_hd_uut/FCLKN_5
add wave -noupdate /test_bench/blue_hd_uut/FCLKN_6
add wave -noupdate /test_bench/blue_hd_uut/FCLKN_7
add wave -noupdate /test_bench/blue_hd_uut/FCLKN_8
add wave -noupdate /test_bench/blue_hd_uut/FCLKN_9
add wave -noupdate /test_bench/blue_hd_uut/FCLKN_10
add wave -noupdate /test_bench/blue_hd_uut/FCLKN_11
add wave -noupdate /test_bench/blue_hd_uut/FCLKN_12
add wave -noupdate /test_bench/blue_hd_uut/FCLKN_13
add wave -noupdate /test_bench/blue_hd_uut/DOUTP_0
add wave -noupdate /test_bench/blue_hd_uut/DOUTP_1
add wave -noupdate /test_bench/blue_hd_uut/DOUTP_2
add wave -noupdate /test_bench/blue_hd_uut/DOUTP_3
add wave -noupdate /test_bench/blue_hd_uut/DOUTP_4
add wave -noupdate /test_bench/blue_hd_uut/DOUTP_5
add wave -noupdate /test_bench/blue_hd_uut/DOUTP_6
add wave -noupdate /test_bench/blue_hd_uut/DOUTP_7
add wave -noupdate /test_bench/blue_hd_uut/DOUTP_8
add wave -noupdate /test_bench/blue_hd_uut/DOUTP_9
add wave -noupdate /test_bench/blue_hd_uut/DOUTP_10
add wave -noupdate /test_bench/blue_hd_uut/DOUTP_11
add wave -noupdate /test_bench/blue_hd_uut/DOUTP_12
add wave -noupdate /test_bench/blue_hd_uut/DOUTP_13
add wave -noupdate /test_bench/blue_hd_uut/DOUTN_0
add wave -noupdate /test_bench/blue_hd_uut/DOUTN_1
add wave -noupdate /test_bench/blue_hd_uut/DOUTN_2
add wave -noupdate /test_bench/blue_hd_uut/DOUTN_3
add wave -noupdate /test_bench/blue_hd_uut/DOUTN_4
add wave -noupdate /test_bench/blue_hd_uut/DOUTN_5
add wave -noupdate /test_bench/blue_hd_uut/DOUTN_6
add wave -noupdate /test_bench/blue_hd_uut/DOUTN_7
add wave -noupdate /test_bench/blue_hd_uut/DOUTN_8
add wave -noupdate /test_bench/blue_hd_uut/DOUTN_9
add wave -noupdate /test_bench/blue_hd_uut/DOUTN_10
add wave -noupdate /test_bench/blue_hd_uut/DOUTN_11
add wave -noupdate /test_bench/blue_hd_uut/DOUTN_12
add wave -noupdate /test_bench/blue_hd_uut/DOUTN_13
add wave -noupdate /test_bench/blue_hd_uut/GF_STV_L
add wave -noupdate /test_bench/blue_hd_uut/GF_STV_LR1
add wave -noupdate /test_bench/blue_hd_uut/GF_STV_LR2
add wave -noupdate /test_bench/blue_hd_uut/GF_STV_LR3
add wave -noupdate /test_bench/blue_hd_uut/GF_STV_LR4
add wave -noupdate /test_bench/blue_hd_uut/GF_STV_LR5
add wave -noupdate /test_bench/blue_hd_uut/GF_STV_LR6
add wave -noupdate /test_bench/blue_hd_uut/GF_STV_LR7
add wave -noupdate /test_bench/blue_hd_uut/GF_STV_LR8
add wave -noupdate /test_bench/blue_hd_uut/GF_STV_R
add wave -noupdate /test_bench/blue_hd_uut/GF_XAO_1
add wave -noupdate /test_bench/blue_hd_uut/GF_XAO_2
add wave -noupdate /test_bench/blue_hd_uut/GF_XAO_3
add wave -noupdate /test_bench/blue_hd_uut/GF_XAO_4
add wave -noupdate /test_bench/blue_hd_uut/GF_XAO_5
add wave -noupdate /test_bench/blue_hd_uut/GF_XAO_6
add wave -noupdate /test_bench/blue_hd_uut/GF_XAO_7
add wave -noupdate /test_bench/blue_hd_uut/GF_XAO_8
add wave -noupdate /test_bench/blue_hd_uut/GF_CPV
add wave -noupdate /test_bench/blue_hd_uut/GF_OE
add wave -noupdate /test_bench/blue_hd_uut/ROIC_AVDD1
add wave -noupdate /test_bench/blue_hd_uut/ROIC_AVDD2
add wave -noupdate /test_bench/blue_hd_uut/PREP_REQ
add wave -noupdate /test_bench/blue_hd_uut/EXP_REQ
add wave -noupdate /test_bench/blue_hd_uut/PREP_ACK
add wave -noupdate /test_bench/blue_hd_uut/EXP_ACK
add wave -noupdate /test_bench/blue_hd_uut/DEBUG_SiG
add wave -noupdate /test_bench/blue_hd_uut/STATE_LED1
add wave -noupdate /test_bench/blue_hd_uut/STATE_LED2
add wave -noupdate /test_bench/blue_hd_uut/s_clk_100mhz
add wave -noupdate /test_bench/blue_hd_uut/s_dphy_clk_200M
add wave -noupdate /test_bench/blue_hd_uut/s_clk_20mhz
add wave -noupdate /test_bench/blue_hd_uut/s_clk_5mhz
add wave -noupdate /test_bench/blue_hd_uut/s_clk_1mhz
add wave -noupdate /test_bench/blue_hd_uut/s_roic_reset
add wave -noupdate /test_bench/blue_hd_uut/s_back_bias
add wave -noupdate /test_bench/blue_hd_uut/s_roic_tp_sel
add wave -noupdate /test_bench/blue_hd_uut/s_roic_sync_in
add wave -noupdate /test_bench/blue_hd_uut/s_roic_sync_out
add wave -noupdate /test_bench/blue_hd_uut/s_roic_a_bz
add wave -noupdate /test_bench/blue_hd_uut/s_roic_sdio
add wave -noupdate /test_bench/blue_hd_uut/eim_clk
add wave -noupdate /test_bench/blue_hd_uut/eim_rst
add wave -noupdate /test_bench/blue_hd_uut/sys_rst
add wave -noupdate /test_bench/blue_hd_uut/rst
add wave -noupdate /test_bench/blue_hd_uut/fsm_drv_rst
add wave -noupdate /test_bench/blue_hd_uut/col_end
add wave -noupdate /test_bench/blue_hd_uut/FSM_rst_index
add wave -noupdate /test_bench/blue_hd_uut/FSM_wait_index
add wave -noupdate /test_bench/blue_hd_uut/FSM_back_bias_index
add wave -noupdate /test_bench/blue_hd_uut/FSM_flush_index
add wave -noupdate /test_bench/blue_hd_uut/FSM_aed_read_index
add wave -noupdate /test_bench/blue_hd_uut/FSM_exp_index
add wave -noupdate /test_bench/blue_hd_uut/FSM_read_index
add wave -noupdate /test_bench/blue_hd_uut/FSM_idle_index
add wave -noupdate /test_bench/blue_hd_uut/FSM_index_all
add wave -noupdate /test_bench/blue_hd_uut/ready_to_get_image
add wave -noupdate /test_bench/blue_hd_uut/aed_ready_done
add wave -noupdate /test_bench/blue_hd_uut/aed_ready_done_dark
add wave -noupdate /test_bench/blue_hd_uut/panel_stable_o
add wave -noupdate /test_bench/blue_hd_uut/s_exp_read_exist
add wave -noupdate /test_bench/blue_hd_uut/row_cnt
add wave -noupdate /test_bench/blue_hd_uut/col_cnt
add wave -noupdate /test_bench/blue_hd_uut/s_sync_col_cnt
add wave -noupdate /test_bench/blue_hd_uut/en_pwr_off
add wave -noupdate /test_bench/blue_hd_uut/en_pwr_dwn
add wave -noupdate /test_bench/blue_hd_uut/system_rst
add wave -noupdate /test_bench/blue_hd_uut/reset_FSM
add wave -noupdate /test_bench/blue_hd_uut/org_reset_FSM
add wave -noupdate /test_bench/blue_hd_uut/dummy_get_image
add wave -noupdate /test_bench/blue_hd_uut/burst_get_image
add wave -noupdate /test_bench/blue_hd_uut/get_dark
add wave -noupdate /test_bench/blue_hd_uut/get_bright
add wave -noupdate /test_bench/blue_hd_uut/cmd_get_bright
add wave -noupdate /test_bench/blue_hd_uut/s_get_bright
add wave -noupdate /test_bench/blue_hd_uut/en_aed
add wave -noupdate /test_bench/blue_hd_uut/s_sum_channel_detected
add wave -noupdate /test_bench/blue_hd_uut/en_panel_stable
add wave -noupdate /test_bench/blue_hd_uut/dsp_image_height
add wave -noupdate /test_bench/blue_hd_uut/max_h_count
add wave -noupdate /test_bench/blue_hd_uut/max_v_count
add wave -noupdate /test_bench/blue_hd_uut/csi2_word_count
add wave -noupdate /test_bench/blue_hd_uut/up_back_bias
add wave -noupdate /test_bench/blue_hd_uut/down_back_bias
add wave -noupdate /test_bench/blue_hd_uut/en_16bit_adc
add wave -noupdate /test_bench/blue_hd_uut/en_test_pattern_col
add wave -noupdate /test_bench/blue_hd_uut/en_test_pattern_row
add wave -noupdate /test_bench/blue_hd_uut/en_test_roic_col
add wave -noupdate /test_bench/blue_hd_uut/en_test_roic_row
add wave -noupdate /test_bench/blue_hd_uut/sig_gate_lr1
add wave -noupdate /test_bench/blue_hd_uut/sig_gate_lr2
add wave -noupdate /test_bench/blue_hd_uut/valid_roic_out
add wave -noupdate /test_bench/blue_hd_uut/valid_roic_burst_clk
add wave -noupdate /test_bench/blue_hd_uut/valid_roic_reg_out
add wave -noupdate /test_bench/blue_hd_uut/valid_roic_header_out
add wave -noupdate /test_bench/blue_hd_uut/valid_roic_data
add wave -noupdate /test_bench/blue_hd_uut/valid_aed_test_data
add wave -noupdate /test_bench/blue_hd_uut/trigger_data_1
add wave -noupdate /test_bench/blue_hd_uut/trigger_data_2
add wave -noupdate /test_bench/blue_hd_uut/trigger_data_3
add wave -noupdate /test_bench/blue_hd_uut/s_pwr_init_step1
add wave -noupdate /test_bench/blue_hd_uut/s_pwr_init_step2
add wave -noupdate /test_bench/blue_hd_uut/s_pwr_init_step3
add wave -noupdate /test_bench/blue_hd_uut/s_pwr_init_step4
add wave -noupdate /test_bench/blue_hd_uut/s_pwr_init_step5
add wave -noupdate /test_bench/blue_hd_uut/s_pwr_init_step6
add wave -noupdate /test_bench/blue_hd_uut/init_rst
add wave -noupdate /test_bench/blue_hd_uut/s_sync_fsm_read_index
add wave -noupdate /test_bench/blue_hd_uut/s_sync_fsm_flush_index
add wave -noupdate /test_bench/blue_hd_uut/s_sync_fsm_back_bias_index
add wave -noupdate /test_bench/blue_hd_uut/s_sync_xao_enable
add wave -noupdate /test_bench/blue_hd_uut/gate_xao
add wave -noupdate /test_bench/blue_hd_uut/gate_xao_0
add wave -noupdate /test_bench/blue_hd_uut/gate_xao_1
add wave -noupdate /test_bench/blue_hd_uut/gate_xao_2
add wave -noupdate /test_bench/blue_hd_uut/gate_xao_3
add wave -noupdate /test_bench/blue_hd_uut/gate_xao_4
add wave -noupdate /test_bench/blue_hd_uut/s_tg_stv
add wave -noupdate /test_bench/blue_hd_uut/s_tg_cpv
add wave -noupdate /test_bench/blue_hd_uut/s_tg_oe
add wave -noupdate /test_bench/blue_hd_uut/s_mask_stv
add wave -noupdate /test_bench/blue_hd_uut/tg_row_cnt
add wave -noupdate /test_bench/blue_hd_uut/tg_col_cnt
add wave -noupdate /test_bench/blue_hd_uut/s_spi_start_flag
add wave -noupdate /test_bench/blue_hd_uut/s_addr_dv
add wave -noupdate /test_bench/blue_hd_uut/s_rw_out
add wave -noupdate /test_bench/blue_hd_uut/s_reg_read_index
add wave -noupdate /test_bench/blue_hd_uut/s_reg_addr
add wave -noupdate /test_bench/blue_hd_uut/s_reg_data
add wave -noupdate /test_bench/blue_hd_uut/s_reg_addr_index
add wave -noupdate /test_bench/blue_hd_uut/s_reg_data_index
add wave -noupdate /test_bench/blue_hd_uut/reg_read_out
add wave -noupdate /test_bench/blue_hd_uut/read_data_en
add wave -noupdate /test_bench/blue_hd_uut/s_reg_read_out_old
add wave -noupdate /test_bench/blue_hd_uut/s_reg_read_out_new
add wave -noupdate /test_bench/blue_hd_uut/s_read_data_en
add wave -noupdate /test_bench/blue_hd_uut/s_reg_address
add wave -noupdate /test_bench/blue_hd_uut/s_read_rx_data_a
add wave -noupdate /test_bench/blue_hd_uut/s_read_rx_data_b
add wave -noupdate /test_bench/blue_hd_uut/s_read_frame_start
add wave -noupdate /test_bench/blue_hd_uut/s_read_frame_reset
add wave -noupdate /test_bench/blue_hd_uut/s_read_axis_tready
add wave -noupdate /test_bench/blue_hd_uut/s_read_axis_tlast
add wave -noupdate /test_bench/blue_hd_uut/s_read_axis_tvalid
add wave -noupdate /test_bench/blue_hd_uut/s_test_cnt
add wave -noupdate /test_bench/blue_hd_uut/s_state_led_ctr
add wave -noupdate /test_bench/blue_hd_uut/s_reg_map_sel
add wave -noupdate /test_bench/blue_hd_uut/s_reset
add wave -noupdate /test_bench/blue_hd_uut/s_csi2_reset
add wave -noupdate /test_bench/blue_hd_uut/s_clk_lock
add wave -noupdate /test_bench/blue_hd_uut/s_csi_done
add wave -noupdate /test_bench/blue_hd_uut/s_axis_video_tuser
add wave -noupdate /test_bench/blue_hd_uut/s_axis_tdata_a
add wave -noupdate /test_bench/blue_hd_uut/s_axis_tdata_b
add wave -noupdate /test_bench/blue_hd_uut/s_reg_tp_sel
add wave -noupdate /test_bench/blue_hd_uut/s_reg_roic_sync
add wave -noupdate /test_bench/blue_hd_uut/ti_roic_sync
add wave -noupdate /test_bench/blue_hd_uut/ti_roic_tp_sel
add wave -noupdate /test_bench/blue_hd_uut/ti_roic_str
add wave -noupdate /test_bench/blue_hd_uut/ti_roic_reg_addr
add wave -noupdate /test_bench/blue_hd_uut/ti_roic_reg_data
add wave -noupdate /test_bench/blue_hd_uut/gen_sync_start
add wave -noupdate /test_bench/blue_hd_uut/s_gen_sync_start_dly
add wave -noupdate /test_bench/blue_hd_uut/s_gen_sync_start_rise
add wave -noupdate /test_bench/blue_hd_uut/ti_roic_deser_reset
add wave -noupdate /test_bench/blue_hd_uut/ti_roic_deser_dly_tap_ld
add wave -noupdate /test_bench/blue_hd_uut/ti_roic_deser_dly_tap_in
add wave -noupdate /test_bench/blue_hd_uut/ti_roic_deser_dly_data_ce
add wave -noupdate /test_bench/blue_hd_uut/ti_roic_deser_dly_data_inc
add wave -noupdate /test_bench/blue_hd_uut/ti_roic_deser_align_mode
add wave -noupdate /test_bench/blue_hd_uut/ti_roic_deser_align_start
add wave -noupdate /test_bench/blue_hd_uut/ti_roic_deser_align_done
add wave -noupdate /test_bench/blue_hd_uut/s_seq_reset
add wave -noupdate /test_bench/blue_hd_uut/seq_lut_addr
add wave -noupdate /test_bench/blue_hd_uut/seq_lut_data
add wave -noupdate /test_bench/blue_hd_uut/seq_lut_wr_en
add wave -noupdate /test_bench/blue_hd_uut/seq_lut_read_data
add wave -noupdate /test_bench/blue_hd_uut/seq_state_read
add wave -noupdate /test_bench/blue_hd_uut/seq_lut_config_done
add wave -noupdate /test_bench/blue_hd_uut/seq_lut_control
add wave -noupdate /test_bench/blue_hd_uut/acq_mode
add wave -noupdate /test_bench/blue_hd_uut/acq_expose_size
add wave -noupdate /test_bench/blue_hd_uut/acq_mode_o
add wave -noupdate /test_bench/blue_hd_uut/expose_size_o
add wave -noupdate /test_bench/blue_hd_uut/s_config_done_i
add wave -noupdate /test_bench/blue_hd_uut/s_sync_config_done
add wave -noupdate /test_bench/blue_hd_uut/exit_signal_i
add wave -noupdate /test_bench/blue_hd_uut/current_state_o
add wave -noupdate /test_bench/blue_hd_uut/busy_o
add wave -noupdate /test_bench/blue_hd_uut/sequence_done_o
add wave -noupdate /test_bench/blue_hd_uut/reset_state_o
add wave -noupdate /test_bench/blue_hd_uut/wait_o
add wave -noupdate /test_bench/blue_hd_uut/bias_enable_o
add wave -noupdate /test_bench/blue_hd_uut/flush_enable_o
add wave -noupdate /test_bench/blue_hd_uut/expose_enable_o
add wave -noupdate /test_bench/blue_hd_uut/readout_enable_o
add wave -noupdate /test_bench/blue_hd_uut/aed_enable_o
add wave -noupdate /test_bench/blue_hd_uut/stv_mask_o
add wave -noupdate /test_bench/blue_hd_uut/csi_mask_o
add wave -noupdate /test_bench/blue_hd_uut/idle_elable_o
add wave -noupdate /test_bench/blue_hd_uut/iterate_exist_o
add wave -noupdate /test_bench/blue_hd_uut/s_wait_sync
add wave -noupdate /test_bench/blue_hd_uut/s_wait_sync_dly
add wave -noupdate /test_bench/blue_hd_uut/s_wait_tp_sel
add wave -noupdate /test_bench/blue_hd_uut/s_wait_roic_sync
add wave -noupdate /test_bench/blue_hd_uut/s_sync_stv_mask_o
add wave -noupdate /test_bench/blue_hd_uut/s_sync_csi_mask_o
add wave -noupdate /test_bench/blue_hd_uut/s_sync_current_repeat_count_o
add wave -noupdate /test_bench/blue_hd_uut/s_sync_repeat_cnt
add wave -noupdate /test_bench/blue_hd_uut/s_sync_repeat_cnt_mod
add wave -noupdate /test_bench/blue_hd_uut/current_sof_o
add wave -noupdate /test_bench/blue_hd_uut/current_eof_o
add wave -noupdate /test_bench/blue_hd_uut/active_repeat_count_o
add wave -noupdate /test_bench/blue_hd_uut/current_repeat_count_o
add wave -noupdate /test_bench/blue_hd_uut/valid_repeat_count_o
add wave -noupdate /test_bench/blue_hd_uut/current_data_length_o
add wave -noupdate /test_bench/blue_hd_uut/s_get_dark_dly
add wave -noupdate /test_bench/blue_hd_uut/s_get_bright_dly
add wave -noupdate /test_bench/blue_hd_uut/s_get_aed_trig_dly
add wave -noupdate /test_bench/blue_hd_uut/s_sequence_done_dly
add wave -noupdate /test_bench/blue_hd_uut/s_get_dark_hi
add wave -noupdate /test_bench/blue_hd_uut/s_get_bright_hi
add wave -noupdate /test_bench/blue_hd_uut/s_get_aed_trig_hi
add wave -noupdate /test_bench/blue_hd_uut/s_sequence_done_hi
add wave -noupdate /test_bench/blue_hd_uut/s_exit_signal_dark
add wave -noupdate /test_bench/blue_hd_uut/s_exit_signal_bright
add wave -noupdate /test_bench/blue_hd_uut/s_exit_signal_aed
add wave -noupdate /test_bench/blue_hd_uut/s_aed_mode_exist
add wave -noupdate /test_bench/blue_hd_uut/s_aed_trig
add wave -noupdate /test_bench/blue_hd_uut/s_aed_trig_i
add wave -noupdate /test_bench/blue_hd_uut/s_valid_readout
add wave -noupdate /test_bench/blue_hd_uut/s_read_data_start
add wave -noupdate /test_bench/blue_hd_uut/s_readout_wait
add wave -noupdate /test_bench/blue_hd_uut/s_state_exit_flag
add wave -noupdate /test_bench/blue_hd_uut/s_aed_detect_skip_oe_o
add wave -noupdate /test_bench/blue_hd_uut/s_miso
add wave -noupdate /test_bench/blue_hd_uut/s_roic_even_odd_out
add wave -noupdate /test_bench/blue_hd_uut/R_ROIC_DCLKo_p
add wave -noupdate /test_bench/blue_hd_uut/R_ROIC_DCLKo_n
add wave -noupdate /test_bench/blue_hd_uut/R_ROIC_FCLKo_p
add wave -noupdate /test_bench/blue_hd_uut/R_ROIC_FCLKo_n
add wave -noupdate /test_bench/blue_hd_uut/R_DOUTA_H
add wave -noupdate /test_bench/blue_hd_uut/R_DOUTA_L
add wave -noupdate /test_bench/blue_hd_uut/ROIC_MCLK1
add wave -noupdate /test_bench/blue_hd_uut/ROIC_VBIAS
add wave -noupdate /test_bench/blue_hd_uut/data_read_req
add wave -noupdate /test_bench/blue_hd_uut/valid_read_enable
add wave -noupdate /test_bench/blue_hd_uut/reordered_valid
add wave -noupdate /test_bench/blue_hd_uut/channel_detected
add wave -noupdate /test_bench/blue_hd_uut/valid_read_mem
add wave -noupdate /test_bench/blue_hd_uut/roic_read_data
add wave -noupdate /test_bench/blue_hd_uut/s_even_odd_toggle_out
add wave -noupdate /test_bench/blue_hd_uut/dbg_even_odd_toggle_out
add wave -noupdate /test_bench/blue_hd_uut/dbg_channel_detected
add wave -noupdate /test_bench/blue_hd_uut/dbg_roic_even_odd
add wave -noupdate /test_bench/blue_hd_uut/dbg_roic_1st_channel
add wave -noupdate /test_bench/blue_hd_uut/s_spidut_en_1d
add wave -noupdate /test_bench/blue_hd_uut/s_spidut_en_2d
add wave -noupdate /test_bench/blue_hd_uut/deser_reset
add wave -noupdate /test_bench/blue_hd_uut/s_spiReady
add wave -noupdate /test_bench/blue_hd_uut/s_rf_spi_sen
add wave -noupdate /test_bench/blue_hd_uut/sdoutWord
add wave -noupdate /test_bench/blue_hd_uut/align_done
add wave -noupdate /test_bench/blue_hd_uut/align_to_fclk
add wave -noupdate /test_bench/blue_hd_uut/align_start
add wave -noupdate /test_bench/blue_hd_uut/s_IRST
add wave -noupdate /test_bench/blue_hd_uut/s_SHR
add wave -noupdate /test_bench/blue_hd_uut/s_SHS
add wave -noupdate /test_bench/blue_hd_uut/s_LPF1
add wave -noupdate /test_bench/blue_hd_uut/s_LPF2
add wave -noupdate /test_bench/blue_hd_uut/s_TDEF
add wave -noupdate /test_bench/blue_hd_uut/s_GATE_ON
add wave -noupdate /test_bench/blue_hd_uut/s_DF_SM0
add wave -noupdate /test_bench/blue_hd_uut/s_DF_SM1
add wave -noupdate /test_bench/blue_hd_uut/s_DF_SM2
add wave -noupdate /test_bench/blue_hd_uut/s_DF_SM3
add wave -noupdate /test_bench/blue_hd_uut/s_DF_SM4
add wave -noupdate /test_bench/blue_hd_uut/s_DF_SM5
add wave -noupdate -divider {reg map}
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/eim_clk
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/eim_rst
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/fsm_clk
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/rst
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/fsm_rst_index
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/fsm_init_index
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/fsm_back_bias_index
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/fsm_flush_index
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/fsm_aed_read_index
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/fsm_exp_index
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/fsm_read_index
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/fsm_idle_index
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/ready_to_get_image
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/aed_ready_done
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/panel_stable_exist
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/exp_read_exist
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/exp_req
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_read_index
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_addr
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_data
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_data_index
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_read_out
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/read_data_en
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/seq_lut_read_data
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/seq_state_read
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/system_rst
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/org_reset_fsm
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reset_fsm
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/en_pwr_dwn
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/en_pwr_off
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/max_v_count
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/max_h_count
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/csi2_word_count
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/ti_roic_sync
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/ti_roic_tp_sel
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/ti_roic_str
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/ti_roic_reg_addr
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/ti_roic_reg_data
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/ti_roic_deser_reset
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/ti_roic_deser_dly_tap_ld
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/ti_roic_deser_dly_tap_in
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/ti_roic_deser_dly_data_ce
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/ti_roic_deser_dly_data_inc
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/ti_roic_deser_align_mode
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/ti_roic_deser_align_start
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/ti_roic_deser_align_shift
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/ti_roic_deser_align_done
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/up_back_bias
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/dn_back_bias
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/seq_lut_addr
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/seq_lut_data
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/seq_lut_wr_en
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/seq_lut_control
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/seq_lut_config_done
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/acq_mode
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/acq_expose_size
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/dsp_image_height
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/get_dark
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/get_bright
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/cmd_get_bright
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/dummy_get_image
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/burst_get_image
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/en_panel_stable
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/en_16bit_adc
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/en_test_pattern_col
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/en_test_pattern_row
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/en_test_roic_col
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/en_test_roic_row
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/exp_ack
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/gate_mode1
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/gate_mode2
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/gate_cs1
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/gate_cs2
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/gate_sel
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/gate_ud
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/gate_stv_mode
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/gate_oepsn
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/gate_lr1
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/gate_lr2
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/stv_sel_h
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/stv_sel_l1
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/stv_sel_r1
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/stv_sel_l2
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/stv_sel_r2
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/state_led_ctr
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/current_reg_addr
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/s_reg_read_out_tmp0
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/s_state_led_ctr
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/FPGA_VER_DATA
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/s_fpga_ver_data
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/CFGCLK
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/DATAVALID
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/fsm_reg
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_sys_cmd_reg
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/sig_reset_fsm_1d
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/hi_reset_fsm
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/lo_reset_fsm
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_pwr_off_dwn
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_max_v_count
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_max_h_count
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_csi2_word_count
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_ti_roic_sync
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_ti_roic_tp_sel
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_ti_roic_str
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_ti_roic_reg_addr
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_ti_roic_reg_data
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_ti_roic_deser_reset
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_ti_roic_deser_dly_tap_ld
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_ti_roic_deser_dly_tap_in
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_ti_roic_deser_dly_data_ce
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_ti_roic_deser_dly_data_inc
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_ti_roic_deser_align_mode
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_ti_roic_deser_align_start
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_ti_roic_deser_align_done
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_seq_lut_addr
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_seq_lut_data_0
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_seq_lut_data_1
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_seq_lut_data_2
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_seq_lut_data_3
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_seq_lut_control
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/seq_lut_data_wr_pulse
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_seq_state_read
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_acq_mode
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_expose_size
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_pre_delay
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_post_delay
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/tmp_expose_size
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_dsp_image_height
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_up_back_bias
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_dn_back_bias
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_op_mode_reg
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/sig_get_bright
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/soft_trigger
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/sig_trigger
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/reg_set_gate
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/dn_aed_gate_xao_0
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/dn_aed_gate_xao_1
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/dn_aed_gate_xao_2
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/dn_aed_gate_xao_3
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/dn_aed_gate_xao_4
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/dn_aed_gate_xao_5
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/up_aed_gate_xao_0
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/up_aed_gate_xao_1
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/up_aed_gate_xao_2
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/up_aed_gate_xao_3
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/up_aed_gate_xao_4
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/up_aed_gate_xao_5
add wave -noupdate /test_bench/blue_hd_uut/reg_map_inst/seq_lut_wr_pulse_cnt
add wave -noupdate -divider {top tb}
add wave -noupdate /test_bench/nRST
add wave -noupdate /test_bench/MCLK_100M_p
add wave -noupdate /test_bench/MCLK_100M_n
add wave -noupdate /test_bench/MCLK_50M_p
add wave -noupdate /test_bench/MCLK_50M_n
add wave -noupdate /test_bench/mipi_phy_if_clk_hs_p
add wave -noupdate /test_bench/mipi_phy_if_clk_hs_n
add wave -noupdate /test_bench/mipi_phy_if_clk_lp_p
add wave -noupdate /test_bench/mipi_phy_if_clk_lp_n
add wave -noupdate /test_bench/mipi_phy_if_data_hs_p
add wave -noupdate /test_bench/mipi_phy_if_data_hs_n
add wave -noupdate /test_bench/mipi_phy_if_data_lp_p
add wave -noupdate /test_bench/mipi_phy_if_data_lp_n
add wave -noupdate /test_bench/SCLK
add wave -noupdate /test_bench/SSB
add wave -noupdate /test_bench/MOSI
add wave -noupdate /test_bench/MISO
add wave -noupdate /test_bench/ROIC_RESET_R
add wave -noupdate /test_bench/ROIC_SYNC_R
add wave -noupdate /test_bench/ROIC_ACLK_R
add wave -noupdate /test_bench/DCLK_R
add wave -noupdate /test_bench/AED_TRIG
add wave -noupdate /test_bench/R_ROIC_DCLKo_p
add wave -noupdate /test_bench/R_ROIC_DCLKo_n
add wave -noupdate /test_bench/R_DOUTA_H
add wave -noupdate /test_bench/R_DOUTA_L
add wave -noupdate /test_bench/R_DOUTB_H
add wave -noupdate /test_bench/R_DOUTB_L
add wave -noupdate /test_bench/GF_STV_L
add wave -noupdate /test_bench/GF_STV_LR2
add wave -noupdate /test_bench/GF_STV_LR3
add wave -noupdate /test_bench/GF_STV_LR4
add wave -noupdate /test_bench/GF_STV_LR5
add wave -noupdate /test_bench/GF_STV_LR6
add wave -noupdate /test_bench/GF_STV_LR7
add wave -noupdate /test_bench/GF_STV_LR8
add wave -noupdate /test_bench/GF_STV_R
add wave -noupdate /test_bench/GF_CPV
add wave -noupdate /test_bench/GF_OE
add wave -noupdate /test_bench/GF_LR1
add wave -noupdate /test_bench/GF_LR2
add wave -noupdate /test_bench/GF_CS1
add wave -noupdate /test_bench/GF_CS2
add wave -noupdate /test_bench/GF_XAO_1
add wave -noupdate /test_bench/GF_XAO_2
add wave -noupdate /test_bench/GF_XAO_3
add wave -noupdate /test_bench/GF_XAO_4
add wave -noupdate /test_bench/GF_XAO_5
add wave -noupdate /test_bench/GF_XAO_6
add wave -noupdate /test_bench/GF_XAO_7
add wave -noupdate /test_bench/GF_XAO_8
add wave -noupdate /test_bench/eim_clk_in
add wave -noupdate /test_bench/R_SW_BIAS
add wave -noupdate /test_bench/L_SW_BIAS
add wave -noupdate /test_bench/RF_SPI_CS_1
add wave -noupdate /test_bench/RF_SPI_CS_2
add wave -noupdate /test_bench/RF_SPI_SCK_1
add wave -noupdate /test_bench/RF_SPI_SDI_1
add wave -noupdate /test_bench/RF_SPI_SDO_1
add wave -noupdate /test_bench/RF_SPI_SCK_2
add wave -noupdate /test_bench/RF_SPI_SDI_2
add wave -noupdate /test_bench/RF_SPI_SDO_2
add wave -noupdate /test_bench/pwr_bbv
add wave -noupdate /test_bench/R_SW_AVDDI
add wave -noupdate /test_bench/L_SW_AVDDI
add wave -noupdate /test_bench/prep_req
add wave -noupdate /test_bench/exp_req
add wave -noupdate /test_bench/prep_ack
add wave -noupdate /test_bench/exp_ack
add wave -noupdate /test_bench/cancel_req
add wave -noupdate /test_bench/led_0
add wave -noupdate /test_bench/led_1
add wave -noupdate /test_bench/led_2
add wave -noupdate /test_bench/led_3
add wave -noupdate /test_bench/led_4
add wave -noupdate /test_bench/led_5
add wave -noupdate /test_bench/led_6
add wave -noupdate /test_bench/led_7
add wave -noupdate /test_bench/osc_clk
add wave -noupdate /test_bench/roic_data_clk
add wave -noupdate /test_bench/m_start
add wave -noupdate /test_bench/slaveselect
add wave -noupdate /test_bench/masterHeader
add wave -noupdate /test_bench/masterAddrToSend
add wave -noupdate /test_bench/masterDataToSend
add wave -noupdate /test_bench/masterDataReceived
add wave -noupdate /test_bench/reset
add wave -noupdate /test_bench/m_sclk_in
add wave -noupdate /test_bench/TI_FCLK_p
add wave -noupdate /test_bench/TI_FCLK_n
add wave -noupdate /test_bench/TI_DCLK_p
add wave -noupdate /test_bench/TI_DCLK_n
add wave -noupdate /test_bench/TI_DOUT_p
add wave -noupdate /test_bench/TI_DOUT_n
add wave -noupdate /test_bench/adc_data
add wave -noupdate /test_bench/adc_data_valid
add wave -noupdate /test_bench/mclk
add wave -noupdate /test_bench/lut_wr_data
add wave -noupdate /test_bench/m_SCLK
add wave -noupdate /test_bench/m_MOSI
add wave -noupdate /test_bench/m_MISO
add wave -noupdate /test_bench/m_CS
add wave -noupdate /test_bench/sv_mipi_phy_if_clk_hs_p
add wave -noupdate /test_bench/sv_mipi_phy_if_clk_hs_n
add wave -noupdate /test_bench/sv_mipi_phy_if_clk_lp_p
add wave -noupdate /test_bench/sv_mipi_phy_if_clk_lp_n
add wave -noupdate /test_bench/sv_mipi_phy_if_data_hs_p
add wave -noupdate /test_bench/sv_mipi_phy_if_data_hs_n
add wave -noupdate /test_bench/sv_mipi_phy_if_data_lp_p
add wave -noupdate /test_bench/sv_mipi_phy_if_data_lp_n
add wave -noupdate /test_bench/clk_100MHz
add wave -noupdate /test_bench/deser_reset
add wave -noupdate /test_bench/test_pass_count
add wave -noupdate /test_bench/test_fail_count
add wave -noupdate /test_bench/expected_data
add wave -noupdate /test_bench/fclk_p
add wave -noupdate /test_bench/mclk_sim
add wave -noupdate /test_bench/dclk_sim
add wave -noupdate /test_bench/sync_counter
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {12154647150 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {66532462500 ps}
