#create_clock -period 20.000 [get_ports MCLK_50M_p]


#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[*]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/static_mrdwr/cur_trn_status_reg/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[*]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/gen_regs.gen_timeout_debug_regs.clk_prepare_reg_axi_reg[*]/CE}]

#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/clock_cross_fifo/gnuram_async_fifo.xpm_fifo_base_inst/rst_d1_inst/d_out_int_reg/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/line_buffer/xpm_fifo_base_inst/gen_pntr_flags_cc.wrp_eq_rdp_pf_cc.gpf_cc_sym.diff_pntr_pf_q_reg[*]/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[*]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/gen_regs.gen_timeout_debug_regs.esc_timeout_axi_reg[*]/CE}]

#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[*]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/static_mrdwr/cur_trn_status_reg/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[*]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/gen_regs.gen_timeout_debug_regs.init_value_axi_reg[*]/CE}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[*]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/gen_regs.gen_timeout_debug_regs.clk_zero_reg_axi_reg[*]/CE}]

#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[*]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/gen_regs.gen_timeout_debug_regs.clk_pre_reg_axi_reg[*]/CE}]

#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[*]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/gen_regs.gen_timeout_debug_regs.clk_trail_reg_axi_reg[*]/CE}]

#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/ATG_SYSINIT_DMG.systeminit_dmg_mask/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[*]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/static_mrdwr/cur_trn_status_reg/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/pktgn_blk/raw20_en_r_reg/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/line_buffer/xpm_fifo_base_inst/gen_sdpram.xpm_memory_base_inst/gen_wr_a.gen_word_narrow.mem_reg_0/ENBWREN}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/clock_cross_fifo/gnuram_async_fifo.xpm_fifo_base_inst/xpm_fifo_rst_inst/gen_rst_ic.wr_rst_busy_ic_reg/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/line_buffer/xpm_fifo_base_inst/rdp_inst/count_value_i_reg[*]/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/line_buffer/xpm_fifo_base_inst/rst_d1_inst/d_out_int_reg/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/line_buffer/xpm_fifo_base_inst/gen_pntr_flags_cc.wrp_eq_rdp_pf_cc.gpf_cc_sym.diff_pntr_pf_q_reg[*]/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/static_mrdwr/cur_trn_addr_reg[*]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/static_mrdwr/max_retry_cntr_reg[*]/R}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/clock_cross_fifo/gnuram_async_fifo.xpm_fifo_base_inst/xpm_fifo_rst_inst/gen_rst_ic.wr_rst_busy_ic_reg/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/line_buffer/xpm_fifo_base_inst/gen_pntr_flags_cc.wrp_eq_rdp_pf_cc.gpf_cc_sym.ram_rd_en_pf_q_reg/D}]

#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/clock_cross_fifo/gnuram_async_fifo.xpm_fifo_base_inst/xpm_fifo_rst_inst/gen_rst_ic.wr_rst_busy_ic_reg/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/line_buffer/xpm_fifo_base_inst/gen_pntr_flags_cc.wrp_eq_rdp_pf_cc.gpf_cc_sym.diff_pntr_pf_q_reg[*]/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[*]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/gen_regs.gen_timeout_debug_regs.hs_prepare_reg_axi_reg[*]/CE}]

#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_data/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[*]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/static_mrdwr/cur_trn_status_reg/D}]

#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[*]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/gen_regs.gen_timeout_debug_regs.dl6_hs_abort_clr_axi_reg/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[*]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/gen_regs.gen_timeout_debug_regs.dl7_esc_abort_clr_axi_reg/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[*]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/gen_regs.gen_timeout_debug_regs.dl7_hs_abort_clr_axi_reg/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[*]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/gen_regs.gen_timeout_debug_regs.dl4_esc_abort_clr_axi_reg/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[*]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/gen_regs.gen_timeout_debug_regs.hs_tx_timeout_axi_reg[*]/CE}]


#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[31]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/gen_regs.gen_timeout_debug_regs.dl2_hs_abort_clr_axi_reg/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[31]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/gen_regs.gen_timeout_debug_regs.dl2_esc_abort_clr_axi_reg/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/pktgn_blk/sync_fifo_rd_en_r1_reg/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/line_buffer/xpm_fifo_base_inst/gen_sdpram.xpm_memory_base_inst/gen_wr_a.gen_word_narrow.mem_reg_1/ENBWREN}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/pktgn_blk/sync_fifo_rd_en_r1_reg/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/line_buffer/xpm_fifo_base_inst/gen_pntr_flags_cc.wrp_eq_rdp_pf_cc.gpf_cc_sym.diff_pntr_pf_q_reg[*]/D}]

#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/clock_cross_fifo/gnuram_async_fifo.xpm_fifo_base_inst/rst_d1_inst/d_out_int_reg/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/line_buffer/xpm_fifo_base_inst/rdpp1_inst/count_value_i_reg[9]/D}]

#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/pktgn_blk/pixel_dn_1_reg/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/line_buffer/xpm_fifo_base_inst/gen_pntr_flags_cc.wrp_eq_rdp_pf_cc.gpf_cc_sym.diff_pntr_pf_q_reg[10]/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/clock_cross_fifo/gnuram_async_fifo.xpm_fifo_base_inst/rst_d1_inst/d_out_int_reg/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/line_buffer/xpm_fifo_base_inst/gen_sdpram.xpm_memory_base_inst/gen_wr_a.gen_word_narrow.mem_reg_0/ENBWREN}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/axi_crossbar_0/inst/gen_sasd.crossbar_sasd_0/addr_arbiter_inst/gen_no_arbiter.grant_rnw_reg/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/static_mrdwr/max_retry_cntr_reg[15]/R}]

#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/pktgn_blk/rgb888_p2b_blk.u_mipi_csi2_tx_ctrl_v1_0_4_rgb888_p2b_blk/rgb888_en_r_reg/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/line_buffer/xpm_fifo_base_inst/gen_pntr_flags_cc.wrp_eq_rdp_pf_cc.gpf_cc_sym.diff_pntr_pf_q_reg[10]/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[*]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/reg_blk/gsp_wr_data_r_reg[*]/CE}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[19]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/gen_regs.gen_timeout_debug_regs.dphy_srst_axi_reg/D}]

#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[21]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/gen_regs.gen_timeout_debug_regs.dl0_esc_abort_clr_axi_reg/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[21]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/gen_regs.gen_timeout_debug_regs.dl1_esc_abort_clr_axi_reg/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[21]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/gen_regs.gen_timeout_debug_regs.dl1_hs_abort_clr_axi_reg/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[*]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/gen_regs.gen_timeout_debug_regs.hs_zero_reg_axi_reg[*]/CE}]

#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/pktgn_blk/sync_fifo_rd_data_cr_reg[*]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/line_buffer/xpm_fifo_base_inst/rdp_inst/count_value_i_reg[*]/CE}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/static_mrdwr/max_retry_cntr_reg[*]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/static_mrdwr/araddr_m_reg[*]/CE}]

#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/clock_cross_fifo/gnuram_async_fifo.xpm_fifo_base_inst/xpm_fifo_rst_inst/gen_rst_ic.wr_rst_busy_ic_reg/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/line_buffer/xpm_fifo_base_inst/rdpp1_inst/count_value_i_reg[9]/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/img_iface/u_mipi_csi2_tx_ctrl_v1_0_4_axis_iface/pxl_vld_ref_r_reg/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/img_iface/u_mipi_csi2_tx_ctrl_v1_0_4_axis_iface/sync_fifo_wr_data_r_reg[9]/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/pktgn_blk/raw14_en_r_reg/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/line_buffer/xpm_fifo_base_inst/gen_pntr_flags_cc.wrp_eq_rdp_pf_cc.gpf_cc_sym.diff_pntr_pf_q_reg[10]/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[20]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/gen_regs.gen_timeout_debug_regs.dl4_hs_abort_clr_axi_reg/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[*]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/gen_regs.gen_timeout_debug_regs.hs_exit_reg_axi_reg[*]/CE}]

#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/static_mrdwr/new_trn_addr_reg[*]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/static_mrdwr/max_retry_cntr_reg[*]/R}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[23]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/gen_regs.gen_timeout_debug_regs.dphy_en_axi_reg/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[23]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/gen_regs.gen_timeout_debug_regs.dl5_esc_abort_clr_axi_reg/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[23]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/gen_regs.gen_timeout_debug_regs.dl5_hs_abort_clr_axi_reg/D}]

#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/axi_crossbar_0/inst/gen_sasd.crossbar_sasd_0/reg_slice_r/m_payload_i_reg[4]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/static_mrdwr/cur_trn_status_reg/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/clock_cross_fifo/gnuram_async_fifo.xpm_fifo_base_inst/rst_d1_inst/d_out_int_reg/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/line_buffer/xpm_fifo_base_inst/rdpp1_inst/count_value_i_reg[9]/CE}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[31]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/gen_regs.gen_timeout_debug_regs.dl1_hs_abort_clr_axi_reg/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[31]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/gen_regs.gen_timeout_debug_regs.dl3_esc_abort_clr_axi_reg/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[*]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/gen_regs.gen_timeout_debug_regs.clk_post_reg_axi_reg[*]/CE}]

#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[25]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/reg_blk/ier_reg[5]/CE}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/static_mrdwr/max_test_time_cntr_reg[*]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/static_mrdwr/awaddr_m_reg[*]/CE}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/static_mrdwr/max_test_time_cntr_reg[*]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/static_mrdwr/wdata_m_reg[*]/CE}]


#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/img_iface/u_mipi_csi2_tx_ctrl_v1_0_4_axis_iface/s_axis_tready_r_reg_rep__1/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/axi_bvalid_reg/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[*]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/gen_regs.gen_timeout_debug_regs.dl3_hs_abort_clr_axi_reg/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[*]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/wr_addr_reg[*]/CE}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[25]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/wr_req_reg/CE}]

#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/clock_cross_fifo/gnuram_async_fifo.xpm_fifo_base_inst/rst_d1_inst/d_out_int_reg/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/line_buffer/xpm_fifo_base_inst/rdp_inst/count_value_i_reg[9]/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/img_iface/u_mipi_csi2_tx_ctrl_v1_0_4_axis_iface/vid_di_cr_reg[*]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/img_iface/u_mipi_csi2_tx_ctrl_v1_0_4_axis_iface/sync_fifo_wr_data_r_reg[*]/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/static_mrdwr/max_retry_cntr_reg[19]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/static_mrdwr/awaddr_m_reg[5]/CE}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[*]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/gen_regs.gen_timeout_debug_regs.dl4_hs_abort_clr_axi_reg/D}]

#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/clock_cross_fifo/gnuram_async_fifo.xpm_fifo_base_inst/xpm_fifo_rst_inst/gen_rst_ic.wr_rst_busy_ic_reg/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/line_buffer/xpm_fifo_base_inst/rdpp1_inst/count_value_i_reg[*]/CE}]

#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/img_iface/u_mipi_csi2_tx_ctrl_v1_0_4_axis_iface/rgb_detect_r_reg/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/img_iface/u_mipi_csi2_tx_ctrl_v1_0_4_axis_iface/sync_fifo_wr_data_r_reg[20]/D}]

#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/img_iface/u_mipi_csi2_tx_ctrl_v1_0_4_axis_iface/rgb_detect_r_reg/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/img_iface/u_mipi_csi2_tx_ctrl_v1_0_4_axis_iface/sync_fifo_wr_data_r_reg[23]/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/img_iface/u_mipi_csi2_tx_ctrl_v1_0_4_axis_iface/pxl_vld_ref_r_reg/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/img_iface/u_mipi_csi2_tx_ctrl_v1_0_4_axis_iface/sync_fifo_wr_data_r_reg[*]/D}]

#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/pktgn_blk/raw8_en_r_reg/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/line_buffer/xpm_fifo_base_inst/gen_pntr_flags_cc.wrp_eq_rdp_pf_cc.gpf_cc_sym.diff_pntr_pf_q_reg[10]/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/pktgn_blk/raw14_en_r_reg/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/line_buffer/xpm_fifo_base_inst/gen_pntr_flags_cc.wrp_eq_rdp_pf_cc.gpf_cc_sym.diff_pntr_pf_q_reg[9]/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[16]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/reg_blk/wr_addr_reg[5]/CE}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[16]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/reg_blk/wr_req_reg/CE}]

#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/pktgn_blk/sync_fifo_rd_data_cr_reg[*]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_csi2_tx_ctrl_0/inst/pktgn_blk/unalgnd_pxl_cntr_reg[*]/R}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[*]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/axi_crossbar_0/inst/gen_sasd.crossbar_sasd_0/reg_slice_r/m_payload_i_reg[*]/CE}]

#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[25]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/gen_regs.gen_timeout_debug_regs.dl3_esc_abort_clr_axi_reg/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[25]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/gen_regs.gen_timeout_debug_regs.dphy_en_axi_reg/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[25]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/gen_regs.gen_timeout_debug_regs.dphy_srst_axi_reg/D}]
#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/systeminit_dmg_addr/xpm_memory_spram_inst/xpm_memory_base_inst/gen_rd_a.gen_rd_a_synth_template.gen_rf_narrow_reg.douta_reg_reg[25]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_csi2_tx_subsyst/inst/mipi_dphy_0/inst/inst/bd_26df_mipi_dphy_0_0_tx_support_i/master_tx.dphy_tx_fab_top/en_regs.gen_regs_wo_debug_wo_timeout.tx_dphy_reg_inst/gen_regs.gen_timeout_debug_regs.dl0_esc_abort_clr_axi_reg/D}]

#set_false_path -from [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/static_mrdwr/max_test_time_cntr_reg[*]/C}] -to [get_pins {inst_mipi_csi2_tx/inst_mipi_csi2_tx/inst_mipi_init_gen/inst/ATG_MODE_SYSTEM_INIT_TEST.systeminit_top/static_mrdwr/araddr_m_reg[*]/CE}]
#set_false_path -from [get_pins {}] -to [get_pins {}]
#set_false_path -from [get_pins {}] -to [get_pins {}]

#set_false_path -from [get_pins {}] -to [get_pins {}]
#set_false_path -from [get_pins {}] -to [get_pins {}]

